name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
       run: sudo apt-get install nasm g++
       
    - name: Go into the source directory.
      run: cd src
      
    - name: Make the compiler
      run: make install

    
